# yaml-language-server: $schema=
# Production overrides
replicaCount: 3
ingress:
  enabled: true

rollout:
  strategy: blueGreen
  blueGreen:
    autoPromotionEnabled: false   # requires manual promotion in ArgoCD UI
app:
  environment: prod
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
